# Generated by Django 5.1.2 on 2024-10-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankloan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc', models.CharField(help_text='acc', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('mobileno', models.IntegerField()),
                ('pancode', models.IntegerField()),
                ('aadharcode', models.IntegerField()),
            ],
        ),
    ]
