# Generated by Django 5.1.2 on 2024-10-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankloan',
            name='id',
        ),
        migrations.AlterField(
            model_name='bankloan',
            name='acc',
            field=models.IntegerField(max_length=20, primary_key='acc', serialize=False),
        ),
    ]
