# Generated by Django 5.1.2 on 2024-10-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0002_remove_bankloan_id_alter_bankloan_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankloan',
            name='acc',
            field=models.IntegerField(primary_key='acc', serialize=False),
        ),
    ]
